# Add 'test' label to any change in tests dir
auto: tests:
- tests/**

auto: docs:
- docs/**

auto: docsrc:
- docsrc/**

auto: core:
- model_compression_toolkit/core/**

auto: data_generation:
- model_compression_toolkit/data_generation/**

auto: exporter:
- model_compression_toolkit/exporter/**

auto: gptq:
- model_compression_toolkit/gptq/**

auto: legacy:
- model_compression_toolkit/legacy/**

auto: ptq:
- model_compression_toolkit/ptq/**

auto: qat:
- model_compression_toolkit/qat/**

auto: target_platform_capabilities:
- model_compression_toolkit/target_platform_capabilities/**

auto: trainable_infrastructure:
- model_compression_toolkit/trainable_infrastructure/**

auto: tutorials:
- tutorials/**

