lsi: false
safe: true
source: model_compression_toolkit
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0

title: model-compression-toolkit
description: Open-source project for neural network model optimization under efficient, constrained hardware