name: License Violation Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '18.12'

    - name: Install Yarn
      run: |
        npm install -g yarn

    - name: Install pnpm
      run: |
        npm install -g pnpm
        echo "$(npm bin -g)" >> $GITHUB_PATH

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Pipenv and Conan
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip setuptools wheel
        pip install pipenv conan scancode-toolkit python-inspector

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods

    - name: Install Bower
      run: |
        npm install -g bower

    - name: Clone and Build ORT
      run: |
        cd ..
        git clone --recurse-submodules https://github.com/oss-review-toolkit/ort.git
        cd ort
        ./gradlew installDist

    - name: Show github workspace
      run: |
        ls -l ${{ github.workspace }}

    - name: Run ORT analyzer
      run: |
        cd ../ort
        ./cli/build/install/ort/bin/ort --info analyze \
          -i ${{ github.workspace }} \
          -o analyzer-output

    - name: Run ORT advisor
      run: |
        cd ../ort
        ./cli/build/install/ort/bin/ort advisor -a OssIndex -i analyzer-output/analyzer-result.yml -o advisor-output 
      

    - name: Run ORT evaluator
      run: |
        cd ../ort
        ls -l
        ls -l ./examples
        ./cli/build/install/ort/bin/ort evaluate \
          --package-curations-file ./examples/curations.yml --rules-file ./examples/evaluator.rules.kts --license-classifications-file ./examples/license-classifications.yml \
          -o evaluator-output


    - name: Generate report
      run: |
        cd ../ort
        ./cli/build/install/ort/bin/ort report \
          -f StaticHtml \
          -i evaluator-output/evaluation-result.yml \
          -o report-output

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: ort-report
        path: ort/report-output/scan-report.html

    - name: Check for rule violations
      run: |
        if grep -q "Rule violation" ort/report-output/scan-report.html; then
          echo "License violations found. Check the report for details."
          exit 1
        else
          echo "No license violations found."
        fi
