name: License Violation Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '18.12'

    - name: Install Yarn
      run: |
        npm install -g yarn

    - name: Install pnpm
      run: |
        npm install -g pnpm
        echo "$(npm bin -g)" >> $GITHUB_PATH

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Pipenv and Conan
      run: |
        python -m pip install --upgrade pip
        pip install pipenv conan

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods

    - name: Install Bower
      run: |
        npm install -g bower

    - name: Create .ort.yml file
      run: |
        cat <<EOL > .ort.yml
        $(cat <<'EOF'
        excludes:
          paths:
            # Exclude gradle-android duplicates
            - pattern: "**/gradle-android/lib/build.gradle"
              reason: "OTHER"
              comment: "Excluding due to duplicate project ID 'Gradle:org.ossreviewtoolkit.gradle.example:lib:1.0.0'"
            - pattern: "**/gradle-android/app/build.gradle"
              reason: "OTHER"
              comment: "Excluding due to duplicate project ID 'Gradle:org.ossreviewtoolkit.gradle.example:app:1.0.0'"
            - pattern: "**/gradle-android/build.gradle"
              reason: "OTHER"
              comment: "Excluding due to duplicate project ID 'Gradle:org.ossreviewtoolkit.gradle.example:Gradle-Android-Example:1.0.0'"
        
            # Exclude gradle duplicates
            - pattern: "**/gradle/build.gradle"
              reason: "OTHER"
              comment: "Excluding due to duplicate project ID 'Gradle::Gradle-Example:'"
            - pattern: "**/gradle/lib/build.gradle"
              reason: "OTHER"
              comment: "Excluding due to duplicate project ID 'Gradle:org.ossreviewtoolkit.gradle.example:lib:1.0.0'"
            - pattern: "**/gradle/app/build.gradle"
              reason: "OTHER"
              comment: "Excluding due to duplicate project ID 'Gradle:org.ossreviewtoolkit.gradle.example:app:1.0.0'"
        
            # Exclude gradle-android-cyclic duplicates
            - pattern: "**/gradle-android-cyclic/build.gradle"
              reason: "OTHER"
              comment: "Excluding due to duplicate project ID 'Gradle:org.ossreviewtoolkit.gradle.example:Gradle-Android-Example:1.0.0'"
            - pattern: "**/gradle-android-cyclic/app/build.gradle"
              reason: "OTHER"
              comment: "Excluding due to duplicate project ID 'Gradle:org.ossreviewtoolkit.gradle.example:app:1.0.0'"
        
            # Exclude gradle-library as it seems to be the source of the original definitions
            - pattern: "**/gradle-library/**/*.gradle"
              reason: "OTHER"
              comment: "This appears to be the source of the original project definitions"
        
        resolutions:
          issues:
            - message: "Multiple projects with the same id .* found"
              reason: "CANT_FIX_ISSUE"
              comment: "Resolved by excluding duplicate project files in the excludes section"
        EOF
        )
        EOL

    - name: Clone and Build ORT
      run: |
        git clone --recurse-submodules https://github.com/oss-review-toolkit/ort.git
        cd ort
        ./gradlew installDist

    - name: Run ORT analyzer
      run: |
        cd ort
        ./cli/build/install/ort/bin/ort --info -P ort.analyzer.allowDynamicVersions=true analyze \
          -i ${{ github.workspace }} \
          -o analyzer-output

    - name: Run ORT scanner
      run: |
        cd ort
        ./cli/build/install/ort/bin/ort scan \
          -i analyzer-output/analyzer-result.yml \
          -o scanner-output

    - name: Run ORT evaluator
      run: |
        cd ort
        ./cli/build/install/ort/bin/ort evaluate \
          -i scanner-output/scan-result.yml \
          -o evaluator-output

    - name: Generate report
      run: |
        cd ort
        ./cli/build/install/ort/bin/ort report \
          -f StaticHtml \
          -i evaluator-output/evaluation-result.yml \
          -o report-output

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: ort-report
        path: ort/report-output/scan-report.html

    - name: Check for rule violations
      run: |
        if grep -q "Rule violation" ort/report-output/scan-report.html; then
          echo "License violations found. Check the report for details."
          exit 1
        else
          echo "No license violations found."
        fi
