name: Coverage Test
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    env:
      COVERAGE_THRESHOLD: 98
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
          pip install pytest
      - name: Prepare TF env
        run: pip install tensorflow==2.13.*
      - name: Run keras pytest
        run: coverage run --parallel-mode -m --omit "*__init__.py" --include "model_compression_toolkit/**/*.py" pytest tests_pytest/keras

      - name: Clear pytest cache
        run: pytest --cache-clear

      - name: Check FOUND_TF before uninstall
        run: |
          python -c "
          from mct_quantizers.common.constants import FOUND_TF
          print(f'FOUND_TF before uninstall: {FOUND_TF}')
          "

      - name: Prepare Torch env
        run: |
          pip uninstall tensorflow -y
          pip list
          pip install torch==2.0.* torchvision onnx onnxruntime onnxruntime-extensions

      - name: Check FOUND_TF before uninstall
        run: |
          python -c "
          from mct_quantizers.common.constants import FOUND_TF
          print(f'FOUND_TF before uninstall: {FOUND_TF}')
          "

      - name: Run torch testsuite
        run: coverage run --parallel-mode -m --omit "*__init__.py" --include "model_compression_toolkit/**/*.py" unittest tests/test_suite.py -v
      - name: Run torch pytest
        run: coverage run --parallel-mode -m --omit "*__init__.py" --include "model_compression_toolkit/**/*.py" pytest tests_pytest/pytorch
      - name: Combine Multiple Coverage Files
        run: coverage combine
      - name: Run Coverage HTML
        run: coverage html -i --directory ./coverage_report_html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: |
            coverage_report_html
      - name: Coverage Report
        run: coverage report -i --skip-covered --sort cover --fail-under $COVERAGE_THRESHOLD
