name: Test pip install
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
#    if: github.repository == 'sony/model_optimization' # Don't do this in forks
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
#      - name: Install dependencies
#        run: |
#          pip install model-compression-toolkit
#          pip install tensorflow
#          pip install tensorflow_model_optimization
      - name: Build nightly
        run: |
          version=$(python -c 'import model_compression_toolkit; print(model_compression_toolkit.__version__)')
          now=$(date +'%d%m%Y-%H%M%S')
          echo "nightly_version=$version.$now" >> $GITHUB_ENV
          sed -i "s/attr: model_compression_toolkit.__version__/$version.$now/g" setup.cfg
          sed -i "s/name='model_compression_toolkit'/name='mct-nightly'/g" setup.py
          python setup.py sdist bdist_wheel
          ls -l
