name: Run Keras Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      tf-version:
        required: true
        type: string

jobs:
  run-tensorflow-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt          
          pip install tensorflow==${{ inputs.tf-version }}
      - name: Run unittests
        run: |
          for script in tests/keras_tests/exporter_tests tests/keras_tests/feature_networks_tests tests/keras_tests/function_tests tests/keras_tests/graph_tests tests/keras_tests/layer_tests; do python -m unittest discover $script -v & pids+=($!); done; for pid in ${pids[@]}; do wait $pid || exit 1; done

