name: Python 3.10, Pytorch 1.13
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *



jobs:
  run-tests:
    uses: ./.github/workflows/run_pytorch_tests.yml
    with:
      python-version: "3.10"
      torch-version: "1.13.*"