name: Python 3.8, Pytorch 2.0
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *


jobs:
  run-tests:
    uses: ./.github/workflows/run_pytorch_tests.yml
    with:
      python-version: "3.8"
      torch-version: "2.0.*"