name: Run Tests - Tensorflow 2.7
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *

jobs:
  run-tensorflow-2_7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/run_keras_tests
        with:
          tf-version: "2.7.*"
