name: 'Scancode io'

on: [pull_request]

permissions:
  contents: read

jobs:
  scancode-io:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: scancode-inputs
      - uses: nexB/scancode-action@alpha
        with:
          pipelines: 'scan_codebase'
          output-formats: 'json xlsx spdx cyclonedx'


