name: 'Scancode io'

on: [pull_request]

permissions:
  contents: read
jobs:
  scan-codebase:
    runs-on: ubuntu-22.04
    name: Scan codebase with ScanCode.io
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install aboutcode-toolkit
        run: |
          pip install aboutcode-toolkit

      - uses: nexB/scancode-action@alpha
        with:
          pipelines: "scan_codebase,find_vulnerabilities"
        env:
          VULNERABLECODE_URL: https://public.vulnerablecode.io/